/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp6;

/**
 *
 * @author Mary
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1Agregar = new javax.swing.JMenuBar();
        jMenu1Cliente = new javax.swing.JMenu();
        jMAgregarCliente = new javax.swing.JMenuItem();
        jMenuItem4BuscarCliente = new javax.swing.JMenuItem();
        jMAgregarTelefono = new javax.swing.JMenuItem();
        jMenuItem6BuscarCliente = new javax.swing.JMenuItem();
        jMenuItem7BorrarCliente = new javax.swing.JMenuItem();
        jMenu2Salir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenu1Cliente.setText("Clientes");
        jMenu1Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ClienteActionPerformed(evt);
            }
        });

        jMAgregarCliente.setText("Agregar Cliente");
        jMAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAgregarClienteActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMAgregarCliente);

        jMenuItem4BuscarCliente.setText("Buscar Cliente");
        jMenuItem4BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4BuscarClienteActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItem4BuscarCliente);

        jMAgregarTelefono.setText("Buscar Telefono");
        jMAgregarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAgregarTelefonoActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMAgregarTelefono);

        jMenuItem6BuscarCliente.setText("Buscar Clientes");
        jMenuItem6BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6BuscarClienteActionPerformed(evt);
            }
        });
        jMenu1Cliente.add(jMenuItem6BuscarCliente);

        jMenuItem7BorrarCliente.setText("Borrar Cliente");
        jMenu1Cliente.add(jMenuItem7BorrarCliente);

        jMenuBar1Agregar.add(jMenu1Cliente);

        jMenu2Salir.setText("Salir");
        jMenuBar1Agregar.add(jMenu2Salir);

        setJMenuBar(jMenuBar1Agregar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6BuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6BuscarClienteActionPerformed

    private void jMenu1ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ClienteActionPerformed
        // TODO add your handling code here:
       
                
    }//GEN-LAST:event_jMenu1ClienteActionPerformed

    private void jMAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAgregarClienteActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        AgregarCliente vacl=new AgregarCliente();
        vacl.setVisible(true);
        escritorio.add(vacl);
        escritorio.moveToFront(vacl);
        
    }//GEN-LAST:event_jMAgregarClienteActionPerformed

    private void jMenuItem4BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4BuscarClienteActionPerformed
      
    }//GEN-LAST:event_jMenuItem4BuscarClienteActionPerformed

    private void jMAgregarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAgregarTelefonoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMAgregarTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMAgregarCliente;
    private javax.swing.JMenuItem jMAgregarTelefono;
    private javax.swing.JMenu jMenu1Cliente;
    private javax.swing.JMenu jMenu2Salir;
    private javax.swing.JMenuBar jMenuBar1Agregar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4BuscarCliente;
    private javax.swing.JMenuItem jMenuItem6BuscarCliente;
    private javax.swing.JMenuItem jMenuItem7BorrarCliente;
    // End of variables declaration//GEN-END:variables
}
